{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "5.3.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.3.21"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.21"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.21"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.21"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "5.3.21"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.21"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-5.3.21.jar",
          "url": "spring-webmvc-5.3.21.jar",
          "size": 1028651,
          "sha512": "381d31077d72625fbb3ed64f4d128f525db16831d5b50a1f2c856eed6c893df17b3ea1160272608a4ef651c0e22b795eb1bd0322d81ec311d9f8a3b92b1187ce",
          "sha256": "fd4a1740d71df048a06bcca0e0b6a04e40b3e677da78757a747e033decf5ed59",
          "sha1": "a62db425cc29c48e138846e706ca37acb138ca13",
          "md5": "498e2da968b40c878ed0c3a18996a655"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.3.21"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.21"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.21"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.21"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "5.3.21"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.21"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-5.3.21.jar",
          "url": "spring-webmvc-5.3.21.jar",
          "size": 1028651,
          "sha512": "381d31077d72625fbb3ed64f4d128f525db16831d5b50a1f2c856eed6c893df17b3ea1160272608a4ef651c0e22b795eb1bd0322d81ec311d9f8a3b92b1187ce",
          "sha256": "fd4a1740d71df048a06bcca0e0b6a04e40b3e677da78757a747e033decf5ed59",
          "sha1": "a62db425cc29c48e138846e706ca37acb138ca13",
          "md5": "498e2da968b40c878ed0c3a18996a655"
        }
      ]
    }
  ]
}
