{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-jpa",
    "version": "2.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.2",
      "buildId": "uizguncohzfczitrlgiwzwrtvi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.9.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.1.jar",
          "url": "spring-boot-starter-data-jpa-2.7.1.jar",
          "size": 4758,
          "sha512": "9e09292dca012d7ad409548683cd7c77115ba02f1d23e4336d313c920c2c92006738fd1ed4032badf7755ec39dbf01333474e698b75ce062e893a0831c99a256",
          "sha256": "e18a5263b1ffbf0aa102e1b5d2d2efff17eb468ef1caf820718fa717ce6433e6",
          "sha1": "39e98264c195a06c8c29a63c24b6ce295ca10795",
          "md5": "90e77060374d9634757f456413906b36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.9.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.1.jar",
          "url": "spring-boot-starter-data-jpa-2.7.1.jar",
          "size": 4758,
          "sha512": "9e09292dca012d7ad409548683cd7c77115ba02f1d23e4336d313c920c2c92006738fd1ed4032badf7755ec39dbf01333474e698b75ce062e893a0831c99a256",
          "sha256": "e18a5263b1ffbf0aa102e1b5d2d2efff17eb468ef1caf820718fa717ce6433e6",
          "sha1": "39e98264c195a06c8c29a63c24b6ce295ca10795",
          "md5": "90e77060374d9634757f456413906b36"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.1.jar",
          "url": "spring-boot-starter-data-jpa-2.7.1.jar",
          "size": 4758,
          "sha512": "9e09292dca012d7ad409548683cd7c77115ba02f1d23e4336d313c920c2c92006738fd1ed4032badf7755ec39dbf01333474e698b75ce062e893a0831c99a256",
          "sha256": "e18a5263b1ffbf0aa102e1b5d2d2efff17eb468ef1caf820718fa717ce6433e6",
          "sha1": "39e98264c195a06c8c29a63c24b6ce295ca10795",
          "md5": "90e77060374d9634757f456413906b36"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "2.7.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.1.jar",
          "url": "spring-boot-starter-data-jpa-2.7.1.jar",
          "size": 4758,
          "sha512": "9e09292dca012d7ad409548683cd7c77115ba02f1d23e4336d313c920c2c92006738fd1ed4032badf7755ec39dbf01333474e698b75ce062e893a0831c99a256",
          "sha256": "e18a5263b1ffbf0aa102e1b5d2d2efff17eb468ef1caf820718fa717ce6433e6",
          "sha1": "39e98264c195a06c8c29a63c24b6ce295ca10795",
          "md5": "90e77060374d9634757f456413906b36"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "2.7.1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.1-javadoc.jar",
          "url": "spring-boot-starter-data-jpa-2.7.1-javadoc.jar",
          "size": 4749,
          "sha512": "ba52666216d6d78bedb77762753c32ee96330d321df29bd2e0718ddd780d93b46f6c113a2ef50e3d4f5d27fd2bd5cd40d5101b4d1c17e0cfddcf5a792eadee63",
          "sha256": "3223c7412ade33222b94ae33536a1ff987324ab803672d94280424a0049a1e52",
          "sha1": "2d07aa9a4befc7ba51e6c1906118cd02202b5a93",
          "md5": "202f933a213c5782a8ee301e445ec4e0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.1-sources.jar",
          "url": "spring-boot-starter-data-jpa-2.7.1-sources.jar",
          "size": 4747,
          "sha512": "e676ceb500106a01ad1d2862c3574a4643f51d6b13259452722362dd678e585ce6db51a09d82ddb874dde69d3510249a28296560a179ff779244c001adee5f36",
          "sha256": "71fb5e3c83e8dab11d8f0963da57066b12a6aef458060c822920e7d9a453ce95",
          "sha1": "622e3ceac2e5bf52580fda13fa86554d1c0d623c",
          "md5": "f19fd67190e73a4c34999b92bd97ec5c"
        }
      ]
    }
  ]
}
