server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/castrohectora/Programa-Advisers.git
          searchPaths: config-datax
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: rootx
      password: pass